# #Reclamation Project - Minutemen Private: rifleman, climbs Private -> PFC -> Specialist.

- type: job
  id: MinutemenPrivate
  setPreference: true
  weight: 70
  displayWeight: 70
  canBeAntag: false
  name: job-name-minutemen-private
  description: job-description-minutemen-private
  playTimeTracker: MinutemenPrivate
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
  startingGear: MinutemenPrivateKitGear
  alwaysUseSpawner: true # #Reclamation Project - spawn at the Minutemen spawn points, late join too
  access:
  - Minutemen
  icon: "JobIconNcrSoldier" # placeholder until Minutemen job icon art exists
  supervisors: job-supervisors-minutemen-officers
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Minutemen
          - Wastelander

- type: playTimeTracker
  id: MinutemenPrivate
