- type: entity
  parent: GrenadeBase
  id: ReclamationGhoulDeploymentGrenade
  name: Synth Reinforcements
  description: Only use in extreme emergencies, calls two Generation One Synths to aid you
  components:
  - type: Sprite
    sprite: Objects/Weapons/Grenades/whiteholegrenade.rsi
  - type: GenericVisualizer
    visuals:
      enum.Trigger.TriggerVisuals.VisualState:
        enum.TriggerVisualLayers.Base:
          Primed: { state: primed }
          Unprimed: { state: icon }
  - type: OnUseTimerTrigger
    delay: 3
  - type: TimerTriggerVisuals
    primingSound:
      path: /Audio/Items/smoke_grenade_prime.ogg
  - type: SpawnOnTrigger
    proto: ReclamationGhoulDeploymentPayload
  - type: SmokeOnTrigger
    duration: 5
    spreadAmount: 9
  - type: SoundOnTrigger
    sound: /Audio/Items/smoke_grenade_smoke.ogg
  - type: DeleteOnTrigger

# Deploy one enforcer and one rifleman.
- type: entity
  id: ReclamationGhoulDeploymentPayload
  categories: [ HideSpawnMenu ]
  components:
  - type: EntityTableSpawner
    table: !type:AllSelector
      children:
      - !type:EntSelector
        id: ReclamationMobGenOneSynthBaton
      - !type:EntSelector
        id: ReclamationMobGenOneSynthLaser
    offset: 0.5
